### PR TITLE
Make ecoinvent SSO client id configurable

### PR DESCRIPTION
**Pull request by jsvgoncalves**
* As requested on #34, this sends a different client id to keycloak

https://github.com/brightway-lca/ecoinvent_interface/issues/34#issuecomment-2401534405

### CODE REVIEW

**Comment by jsvgoncalves** [comment]
@asergios My guess is the client id isn't configured on keycloak yet?

**Comment by asergios** [comment]
> @asergios My guess is the client id isn't configured on keycloak yet?

Just took care of it now, give it a try!

**Comment by jsvgoncalves** [comment]
@asergios there seems to still be something wrong in the reply back from apollo

**Comment by asergios** [comment]
@jsvgoncalves Sorry for the late reply. `offline_access` was indeed missing for the new client. I tested locally and seems to be fine now. Can you re-run the tests please?

**Comment by jsvgoncalves** [comment]
> Sorry for the late reply. `offline_access` was indeed missing for the new client. I tested locally and seems to be fine now. Can you re-run the tests please?

Cool, tests are passing on CI too. https://github.com/brightway-lca/ecoinvent_interface/actions/runs/12008197826

**Comment by tngTUDOR** [comment]
This makes `ecoinvent_interface` provide a different client id to the target API, not a fix for #34

**Comment by tngTUDOR** [comment]
@jsvgoncalves did we miss a spot:

 https://github.com/brightway-lca/ecoinvent_interface/blob/76c5badd885b7b1c976c4a9f3d58f99508334060/ecoinvent_interface/core.py#L189

**Comment by jsvgoncalves** [comment]
> @jsvgoncalves did we miss some spots?
> 
> https://github.com/brightway-lca/ecoinvent_interface/blob/76c5badd885b7b1c976c4a9f3d58f99508334060/ecoinvent_interface/core.py#L189
> 
> https://github.com/brightway-lca/ecoinvent_interface/blob/76c5badd885b7b1c976c4a9f3d58f99508334060/ecoinvent_interface/core.py#L279
> 
> https://github.com/brightway-lca/ecoinvent_interface/blob/76c5badd885b7b1c976c4a9f3d58f99508334060/ecoinvent_interface/core.py#L299
> 
> _Or_ there is no difference or trouble when using a client-id and a different api-library.

Correct, the header that keycloak needs is the `client_id`. The `ecoinvent-api-client-library` was just a temporary nicety for ecoinvent folks to be able to tell the requests coming from this library apart, i.e. it's non-functional.

**Comment by asergios** [comment]
> We won't disable `Direct Grant` from `apollo-ui` for now to allow users of `ei-interface` to migrate to a more recent version where `brightway-ei` is used instead.
> 
> What do you think is a reasonable time for that? 3 months?

@cmutel FYI I will pull the switch on 1st of March

**Comment by cmutel** [comment]
@asergios Thanks a lot, I will bump the required version in our libraries and let the community know.

**Pull request merged**
